# -*- coding: utf-8 -*-
"""bot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FIYdBmeLL4YYseGRScaJGOQyhuVQUYoM
"""

# bot.py
import asyncio
import logging
import nest_asyncio

from aiogram import Bot, Dispatcher
from aiogram.filters.command import Command
from aiogram import F

from config import API_TOKEN
from database import create_tables
from handlers import cmd_start, answer_callback, start_quiz, send_question

# Фикс для работы в Jupyter/Colab
nest_asyncio.apply()

# Настройка логирования
logging.basicConfig(level=logging.INFO)

# Инициализация бота
bot = Bot(token=API_TOKEN)
dp = Dispatcher()

# Регистрация handlers
dp.message(Command("start"))(cmd_start)
dp.message(F.text == "Начать квиз")(start_quiz)
dp.message(Command("quiz"))(start_quiz)
dp.callback_query(F.data.startswith("option_"))(answer_callback)


# Основная функция
async def main():
    await create_tables()  # Создание таблиц
    await dp.start_polling(bot)

# Запуск приложения
if __name__ == "__main__":
    asyncio.run(main())