# -*- coding: utf-8 -*-
"""config

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PcUpasKY5ik_sYLCENcrrvn_9o-hRJPY
"""

# config.py
API_TOKEN = '7608587785:AAGXO3e-pH9OVVW2mR_LvkkcR-ofq0S--ms'
DB_NAME = 'quiz_bot.db'
QUIZ_FILE = 'quiz_data.json'