# -*- coding: utf-8 -*-
"""database

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YJ_DvNoJynf9yyaBSb9G04LSuvXUAzlE
"""

# database.py
import aiosqlite
import logging
from config import DB_NAME
from aiogram import Bot, types  # Импорт бота и его типов

async def create_tables():
    async with aiosqlite.connect(DB_NAME) as db:
        try:
            await db.execute('''CREATE TABLE IF NOT EXISTS quiz_state (
                              user_id INTEGER PRIMARY KEY,
                              question_index INTEGER,
                              score INTEGER DEFAULT 0)''')  # Добавляем поле score
            await db.execute('''CREATE TABLE IF NOT EXISTS quiz_results (
                              user_id INTEGER PRIMARY KEY,
                              last_score INTEGER)''')
            await db.commit()
            logging.info("Database tables created or checked successfully.")

        except aiosqlite.Error as e:
            logging.error(f"Error creating database tables: {e}")

async def get_quiz_index(user_id):
    async with aiosqlite.connect(DB_NAME) as db:
        try:
            async with db.execute('SELECT question_index FROM quiz_state WHERE user_id = ?', (user_id,)) as cursor:
                result = await cursor.fetchone()
                return result[0] if result else 0
        except aiosqlite.Error as e:
            logging.error(f"Error getting quiz index for user {user_id}: {e}")
            return 0


async def update_quiz_index(user_id, index):
    async with aiosqlite.connect(DB_NAME) as db:
        try:
            await db.execute('INSERT OR REPLACE INTO quiz_state (user_id, question_index, score) VALUES (?, ?, ?) ON CONFLICT(user_id) DO UPDATE SET question_index = ?, score = score', (user_id, index, await get_user_score(user_id), index)) # Сохраняет существующий счет
            await db.commit()
            logging.info(f"User {user_id}: Quiz index updated to {index}")
        except aiosqlite.Error as e:
            logging.error(f"Error updating quiz index for user {user_id}: {e}")



async def get_user_score(user_id):
    async with aiosqlite.connect(DB_NAME) as db:
        try:
            async with db.execute('SELECT score FROM quiz_state WHERE user_id = ?', (user_id,)) as cursor:
                result = await cursor.fetchone()
                return result[0] if result else 0
        except aiosqlite.Error as e:
            logging.error(f"Error getting score for user {user_id}: {e}")
            return 0


async def update_user_score(user_id, score):
    async with aiosqlite.connect(DB_NAME) as db:
        try:
            await db.execute('INSERT OR REPLACE INTO quiz_state (user_id, question_index, score) VALUES (?, ?, ?) ON CONFLICT(user_id) DO UPDATE SET score = ?', (user_id, await get_quiz_index(user_id), score, score))
            await db.commit()
            logging.info(f"User {user_id}: Score updated to {score}")
        except aiosqlite.Error as e:
            logging.error(f"Error updating score for user {user_id}: {e}")

async def save_quiz_result(user_id):
    # Получаем финальный счет пользователя
    final_score = await get_user_score(user_id)
    async with aiosqlite.connect(DB_NAME) as db:
        try:
            await db.execute('INSERT OR REPLACE INTO quiz_results (user_id, last_score) VALUES (?, ?)', (user_id, final_score))
            await db.commit()
            logging.info(f"User {user_id}: Quiz result saved with score {final_score}")
        except aiosqlite.Error as e:
            logging.error(f"Error saving quiz result for user {user_id}: {e}")

async def show_leaderboard(message:types.Message, bot:Bot):  # Добавлен аргумент bot типа Bot
    async with aiosqlite.connect(DB_NAME) as db:
        try:
            async with db.execute('SELECT user_id, last_score FROM quiz_results ORDER BY last_score DESC LIMIT 5') as cursor:
                leaders = await cursor.fetchall()

            leaderboard = "🏆 Топ игроков:\n"
            for i, (user_id, score) in enumerate(leaders, 1):
                try:
                    chat_member = await bot.get_chat_member(chat_id=message.chat.id, user_id=user_id) # получение информации об участнике чата для доступа к имени пользователя

                    if chat_member.status != "left" and chat_member.status != "kicked": # если пользователь не ушел или его не выгнали
                        user = chat_member.user
                        leaderboard += f"{i}. {user.username or user.first_name or user.id}: {score} баллов\n" # получение имени пользователя, если оно доступно, или имени отчества, если его нет
                    else:
                        leaderboard += f"{i}. User ID: {user_id} (Пользователь покинул чат): {score} баллов\n" # если оставить, то будет отображаться идентификатор пользователя

                except Exception as e:
                    # Обработка ошибки, если не удается получить информацию о пользователе
                    leaderboard += f"{i}. User ID: {user_id} (Не удалось получить имя): {score} баллов\n"

            return leaderboard

        except aiosqlite.Error as e:
            logging.error(f"Error showing leaderboard: {e}")
            return "Произошла ошибка при отображении таблицы лидеров."