# -*- coding: utf-8 -*-
"""handlers

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cBQlBd7uU2-Yzi5ElcMH04lDosn0diCD
"""

# handlers.py
import logging
from aiogram import types, F, Bot
from aiogram.filters.command import Command
from aiogram.utils.keyboard import ReplyKeyboardBuilder
from database import get_quiz_index, update_quiz_index, get_user_score, update_user_score, save_quiz_result, show_leaderboard
from quiz_data import quiz_data
from keyboards import generate_options_keyboard
from config import API_TOKEN

bot = Bot(token=API_TOKEN) # Бот необходим для получения информации о чате (таблица лидеров)

# Обработчик ответов
async def answer_callback(callback: types.CallbackQuery):
    user_id = callback.from_user.id
    selected_option = int(callback.data.split('_')[1])

    current_question_index = await get_quiz_index(user_id)
    correct_option = quiz_data[current_question_index]['correct_option']

    # Получаем текущий счет пользователя
    score = await get_user_score(user_id)
    logging.info(f"User {user_id}: Current score = {score}")

    # Удаляем кнопки
    await callback.message.edit_reply_markup(reply_markup=None)

    # Проверка ответа
    if selected_option == correct_option:
        await callback.message.answer("✅ Верно!")
        # Увеличиваем счет пользователя
        score += 1
        logging.info(f"User {user_id}: Correct answer! New score = {score}")
        await update_user_score(user_id, score)
    else:
        correct_answer = quiz_data[current_question_index]['options'][correct_option]
        await callback.message.answer(f"❌ Неверно! Правильный ответ: {correct_answer}")
        logging.info(f"User {user_id}: Incorrect answer. Score remains {score}")

    # Переход к следующему вопросу
    current_question_index += 1
    await update_quiz_index(user_id, current_question_index)

    if current_question_index < len(quiz_data):
        await send_question(callback.message, user_id)
    else:
        await callback.message.answer("🏁 Квиз завершен!")
        await save_quiz_result(user_id)
        leaderboard = await show_leaderboard(callback.message, bot) # # Получаем таблицу лидеров из БД, передавая сообщение и бота.
        await callback.message.answer(leaderboard) # отправьте его пользователю

# Команда /start
async def cmd_start(message: types.Message):
    builder = ReplyKeyboardBuilder()
    builder.add(types.KeyboardButton(text="Начать квиз"))
    await message.answer("Добро пожаловать в квиз-бот! 🎮", reply_markup=builder.as_markup(resize_keyboard=True))

# Отправка вопроса
async def send_question(message, user_id):
    current_index = await get_quiz_index(user_id)
    question = quiz_data[current_index]
    keyboard = generate_options_keyboard(question['options'])
    await message.answer(f"❓ Вопрос {current_index + 1}/{len(quiz_data)}:\n\n{question['question']}", reply_markup=keyboard)

# Запуск нового квиза
async def start_quiz(message: types.Message):
    user_id = message.from_user.id
    await update_quiz_index(user_id, 0)
    # Сбрасываем счет пользователя при начале нового квиза
    await update_user_score(user_id, 0)
    logging.info(f"User {user_id}: Starting new quiz. Score reset to 0.")
    await message.answer("🚀 Начинаем квиз!")
    await send_question(message, user_id)