# -*- coding: utf-8 -*-
"""quiz_data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10h3K4eyzkf_h_Gu_bMtMGtqdiLyvmDc7
"""

# quiz_data.py
import json
import os

QUIZ_FILE = 'quiz_data.json'


def load_quiz_data(file_path=QUIZ_FILE):
    if os.path.exists(file_path):
        with open(file_path, 'r', encoding='utf-8') as file:
            return json.load(file)
    else:
        return [
            {
                'question': 'Что такое Python?',
                'options': ['Язык программирования', 'Тип данных', 'Музыкальный инструмент', 'Змея'],
                'correct_option': 0
            },
            {
                'question': 'Какая функция используется для вывода текста в консоль в Python?',
                'options': ['print()', 'display()', 'write()', 'show()'],
                'correct_option': 0
            },
            {
                'question': 'Что такое переменная в программировании?',
                'options': ['Константа', 'Ячейка памяти для хранения данных', 'Функция', 'Комментарий'],
                'correct_option': 1
            },
            {
                'question': 'Какой метод используется для добавления элемента в конец списка в Python?',
                'options': ['add()', 'append()', 'insert()', 'push()'],
                'correct_option': 1
            },
            {
                'question': 'Что выведет следующий код: `print(type([1, 2, 3]))`?',
                'options': ["<class 'tuple'>", "<class 'list'>", "<class 'array'>", "<class 'set'>"],
                'correct_option': 1
            },
            {
                'question': 'Какой оператор используется для проверки равенства двух значений в Python?',
                'options': ['=', '==', '!=', 'is'],
                'correct_option': 1
            },
            {
                'question': 'Что такое lambda-функция в Python?',
                'options': ['Анонимная функция', 'Функция для работы с графикой', 'Функция для работы с базами данных', 'Функция для импорта модулей'],
                'correct_option': 0
            },
            {
                'question': 'Как получить длину строки в Python?',
                'options': ['string.length()', 'len(string)', 'string.size()', 'size(string)'],
                'correct_option': 1
            },
            {
                'question': 'Для чего используется конструкция `try...except` в Python?',
                'options': ['Для создания циклов', 'Для обработки исключений', 'Для определения функций', 'Для импорта модулей'],
                'correct_option': 1
            },
            {
                'question': 'Что такое PEP 8?',
                'options': ['Название змеи в Python', 'Руководство по стилю написания кода на Python', 'Тип данных в Python', 'Инструмент для отладки кода'],
                'correct_option': 1
            }
        ]


quiz_data = load_quiz_data()